package com.example.LatteList.Enums;

public enum Etiquetas {
        CAFE_ESPECIALIDAD,
        CAFE_COMERCIAL,
        TOSTADO_PROPIO,
        ORGANICO,
        BLEND_EXCLUSIVO,
        PASTELERIA_FRANCESA,
        PASTELERIA_ITALIANA,
        VEGANO,
        VEGETARIANO,
        SIN_TACC,
        APTO_CELIACOS,
        BRUNCH,
        TEMATICO,
        MINIMALISTA,
        VINTAGE,
        PET_FRIENDLY,
        LIBROS,
        ARTE,
        MUSICA_EN_VIVO,
        ESTILO_COWORKING,
        FRENTE_AL_MAR,
        ZONA_CENTRICA,
        WIFI,
        ENCHUFES_DISPONIBLES,
        TERRAZA,
        PATIO,
        CALEFACCION,
        AUIRE_ACONDICIONADO,
        ESTUDIANTES,
        GRUPOS_GRANDES,
        FAMILIAR,
        PAREJAS ;
    }

